### ISSUE TITLE
Mk3 impassable

### ISSUE THREAD

**Issue by jamieT06** [codepoetpbowden/ConnectedLivingSpace#66]
So the issue is that MK3 parts have no none tank adapters, by default fuel tanks are impassible which makes sense. Except the mk3 fuel tanks all have doors in them for fuel transfer. any chance of CIS not restricting mk3 part transfers

**Comment by PapaJoesSoup** [comment]
These parts are by design impassable.  If you wish to have that capability, simply create a config for it. 

Sample config here:
`@PART[Mark2Cockpit]:HAS[!MODULE[ModuleConnectedLivingSpace]]
{
	MODULE
	{
		name = ModuleConnectedLivingSpace
		passable = true
	}
}
`
Replace Mark2Cocpit with the name of the part that you wish to change.  save into a .cfg file.  Place it in the GameData folder (you could put it in any folder under Gamedata, but best to put it in the GameData Folder so that subsequent releases of CLS do not remove the file you create.

**Comment by jamieT06** [comment]
Helpful thanks
