### ISSUE TITLE
Separate spaces when docked

### ISSUE THREAD

**Issue by racer01** [codepoetpbowden/ConnectedLivingSpace#75]
In **stock** KSP **v1.1.3**.1289 (gog/Windows version), **CLS v1.2.3.0** (installed via CKAN) does not merge spaces upon docking and hatch opening, with every save (even new). In **CLS v1.2.2.1** it **works fine**. 
It can be reproduced by making a single craft from bottom to top like [Mk2 Lander Can] -> [Clamp-O-Tron Docking Port] -> [upside down Clamp-O-Tron Docking Port] ->[upside down Mk2 Lander Can]. 
![clstest](https://cloud.githubusercontent.com/assets/14020544/18751184/5e71ea3a-80de-11e6-9630-88ab5a08b38e.gif)

![screenshot63](https://cloud.githubusercontent.com/assets/14020544/18751295/ca6b02da-80de-11e6-8ca5-d4632a1079ae.png)
Then decouple, and fly away a bit to re-engage docking ports
![screenshot64](https://cloud.githubusercontent.com/assets/14020544/18751297/ca6d468a-80de-11e6-9ece-972dbc850734.png)
After redocking, and opening hatches
![screenshot65](https://cloud.githubusercontent.com/assets/14020544/18751296/ca6cc50c-80de-11e6-9385-d7309375f7ed.png)

**Comment by PapaJoesSoup** [comment]
Corrected with v1.2.4.1

**Comment by evanrinehart** [comment]
Hello on KSP 1.7 two connected living spaces with docking ports do not become one. Crew are not allowed to transfer through the docking port before or after the hatches are opened. If you check "allow unrestricted transfer", open the hatches, then transfer crew, the two spaces before one and stay one regardless of hatch state until they undock.

I believe this issue was for the same problem despite the screenshots being about ships pre-built to be docked. If not I can make a new issue.
